name: wos
description: 我搜
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.2.0"

dependencies:
    about: ^2.0.0
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    epubx: ^3.0.0
    file_picker: ^4.5.1+3
    flutter_displaymode: ^0.5.0
    hive_flutter: ^1.1.0
    oktoast: ^3.0.0
    path_provider: ^2.0.1
    permission_handler: ^7.0.0
    provider: ^5.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    # flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/assets/
    fonts:
        - family: fonticons
          fonts:
              - asset: fonts/fonticons.ttf
